### ISSUE TITLE
Layer Channel_attention has arguments in __init__ and therefore must override get_config

### ISSUE THREAD

**Issue by sandeepgitam** [laugh12321/3D-Attention-Keras#2]
`NotImplementedError: 
Layer spatial_attention has arguments ['self', 'kernel_size']
in `__init__` and therefore must override `get_config()`.`

Can you please resolve this error that is coming after the first epoch during training.

**Comment by laugh12321** [comment]
Problem solved 👉 [🐛Fix NotImplementedError](https://github.com/laugh12321/3D-Attention-Keras/commit/49965842f9bb0b19d7a5eb7632099915255c2d82)
